In [1]:
import torch
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
tensor = torch.tensor(arr)

tensor

tensor([1, 2, 3, 4, 5])

In [9]:
# 0~1 正态分布 第一位参数是可变参数 可 int、list、tuple
tensor1 = torch.randn([2,2])
tensor1

tensor([[-1.1858,  0.6407],
        [-0.3343, -1.2511]])

In [10]:
# 0~1 均匀分布
tensor2 = torch.rand((1,2))
tensor2

tensor([[0.9876, 0.5940]])

In [16]:
tensor3 = torch.normal(1,2,(2,3))
tensor3

tensor([[-0.4422,  2.1922, -0.8501],
        [-1.6369,  1.7074,  1.2979]])

In [21]:
tensor4 = torch.normal(1,torch.arange(1,5,dtype=torch.float))
tensor4

tensor([ 0.5277,  2.5226,  3.0325, -1.8264])

In [22]:
tensor5 = torch.normal(torch.arange(1,5,dtype=torch.float),2)
tensor5

tensor([2.6707, 1.3915, 3.1782, 5.1394])

In [27]:
# 自己设置step
t6 = torch.arange(torch.tensor(1),5,1, dtype=torch.float)
# 等间距
t7 = torch.linspace(1,5,4,dtype=torch.float)

print(t6,t7)

tensor([1., 2., 3., 4.]) tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [31]:
torch.manual_seed(1)
tt1 = torch.rand(1,2)
print(tt1)
torch.manual_seed(1)
tt2 = torch.rand(1,2)
print(tt2)

tensor([[0.7576, 0.2793]])
tensor([[0.7576, 0.2793]])


In [35]:
tt3 = torch.eye(6,3)
tt3

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])